#!/usr/bin/env bash
#runs the whoami command under the user passed as argument.
if [ "$#" -ne 1 ]; then
  echo "Usage: $0 <username>"
  exit 1
fi

# Get the username from the argument
USER=$1

sudo -c 'whoami' $USER
